/**
 * ESLint flat config (ESLint 9).
 *
 * Deliberately small. Architecture §92 rule 12 prefers simple, testable
 * modules over abstraction-heavy tooling, and rule 11 says not to introduce
 * infrastructure before a real requirement exists — so this is typescript-eslint
 * recommended plus a few rules that encode project-specific hazards found during
 * the scaffold. No stylistic/formatting rules: Prettier owns formatting.
 */
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/coverage/**',
      '**/node_modules/**',
      '**/playwright-report/**',
      '**/test-results/**',
      // Generated by Prisma from schema.prisma.
      'packages/database/src/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ---- Node-side TypeScript (api, packages) ----
  {
    files: ['apps/api/**/*.ts', 'packages/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  // ---- Browser-side TypeScript (web) ----
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser },
    },
  },

  // ---- Test files ----
  {
    files: ['**/*.test.ts', '**/*.test.tsx', 'tests/**/*.ts'],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  {
    rules: {
      // Unused code is a defect signal in a project this new.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // `any` erases the type safety the whole stack depends on.
      '@typescript-eslint/no-explicit-any': 'error',

      // Enforce explicit return types on exported functions only — enough to
      // keep the public contract readable without demanding types everywhere.
      '@typescript-eslint/explicit-module-boundary-types': 'off',

      // Floating promises hide unhandled rejections.
      'no-console': ['warn', { allow: ['warn', 'error', 'info'] }],
    },
  },

  // ---- React app rules ----
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: {},
    rules: {
      // React 18 with the automatic JSX runtime does not need React in scope.
      'no-undef': 'off',
    },
  },

  // ---- Seed and E2E specs may log freely ----
  {
    files: ['packages/database/prisma/seed.ts', 'tests/e2e/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
);